### ISSUE TITLE
Add whitespace handshake notification

### ISSUE THREAD

**Issue by 9Z8LwVMdctC630D0gAWmmFHe1nR** [python-otr/pure-python-otr#41]
An additional notification should be added when a user sends a message in plaintext that contains the OTR whitespace handshake.

This should happen so a user is aware that he is sending a plaintext message, since sometimes it is possible the OTR icon will be displayed but a message may be send unencrypted with the OTR handshake.

Additionally it is nice for a user to know that his unencrypted message had the whitespace handshake.

One way to add this in otrmodule.py, change the try/except inside handle_outgoing_msg to:

```
    try:
        newmsg = self.us[event.account].getContext(fjid).sendMessage(
                potr.context.FRAGMENT_SEND_ALL_BUT_LAST, message,
                appdata={'session':event.session})
        if ' \t  \t\t\t\t \t \t \t  ' in newmsg:
                self.gajim_log(_('The following message was sent unencrypted '
                'and contains an OTR whitespace handshake:'), event.account,
                fjid)
        potrrootlog.debug('processed message={0!r}'.format(newmsg))
```

**Comment by koolfy** [comment]
This does not relate to the library itselt but downstream client implementations

Gajim otr plugin code has been moved here: https://dev.gajim.org/gajim/gajim-plugins/wikis/OffTheRecordPlugin
