### ISSUE TITLE
Traceback on unknown TLV

### ISSUE THREAD

**Issue by mathieui** [python-otr/pure-python-otr#60]
ChatSecure uses [custom TLV values](https://dev.guardianproject.info/projects/gibberbot/wiki/OTRDATA_Specifications) for their OTRDATA protocol, and it exposed a bug in potr:
```python
   File "/usr/lib64/python3.4/site-packages/potr/context.py", line 225, in receiveMessage
     plaintext, tlvs = self.crypto.handleDataMessage(message)
   File "/usr/lib64/python3.4/site-packages/potr/crypt.py", line 192, in handleDataMessage
     tlvs = proto.TLV.parse(tlvData)
   File "/usr/lib64/python3.4/site-packages/potr/proto.py", line 319, in parse
     return [tlvClasses[typ].parsePayload(data[:length])] \
 KeyError: 256
```
potr should check if the received TLVs are known before trying to get the relevant class. (and maybe return a custom exception when it isn’t known?)

**Comment by koolfy** [comment]
We should actually raise NotOTRMessage as it's used in the rest of the code.
I'm looking into why it's not the case here exactly, and fix this quickly :)

**Comment by koolfy** [comment]
Possible fix to test: https://github.com/python-otr/pure-python-otr/commit/1422de3cda9632a994dbc5d575990e384f048971

I basically just implemented a new exception (insead of reusing NotOTRMessage which I didn't find to fit the bill quite right), and added a check against registered values of implemented TLV in the tlvClasses dict.

**Comment by mathieui** [comment]
Yes, looks good to me

**Comment by koolfy** [comment]
Great, I'm currently at 32C3 and (intentionally) don't have github credentials on my person :)
As soon as I get back, I'll merge the branch and prepare a new release.

**Comment by koolfy** [comment]
Merged in staging, closing for now.
