### ISSUE TITLE
automatically end OTR session when contact does

### ISSUE THREAD

**Issue by azrdev** [python-otr/pure-python-otr#61]
When a contact closes his OTR session with me, I get (in gajim) the message "OTR: $contact has ended his/her private conversation with you. You should do the same."

I'd expect my client to close my session automatically in that case

**Comment by tribut** [comment]
This is a security feature. Think of the scenario where you have established an OTR session and you are typing a message. The peer closes the session and you try to send your message. If the client would automatically cancel your otr session you would send your message unencrypted (unless `REQUIRE_ENCRYPTION` is set).

You could argue that when no conversation window is open when the peer terminates the session this is a non-issue, but then this should be discussed with the developers of the client (or plugin), not here.

**Comment by azrdev** [comment]
@tribut ack. How about introducing a timeout before ending the private connection?

**Comment by afflux** [comment]
While this can be a reasonable option for clients, we shouldn't have this in the library.
